import argparse
args = argparse.ArgumentParser()
args.add_argument("--dataset", type=str, default='openssl', help="dataset")
args.add_argument("--encodeset", type=str, default='kernel', help="dataset")
# args.add_argument("--mode", type=str, default='inner', help="encode type inner/inter/unlimited")
args.add_argument("--epochs", type=int, default=100, help="# of epochs")
args.add_argument("--batch_size", type=int, default=512, help="batch size for sgd")
args.add_argument("--channel", type=int, default=24, help="# of channels")
args.add_argument("--mtc",  action="store_true", default=False, help="does we use multi channel as for input")
args.add_argument("--embed_dim", type=int, default=256, help="output dimension")
args.add_argument("--in_dim", type=int, default=86, help="input dimension")
args.add_argument("--traintest",  type=str, default="test")
args.add_argument("--save_model", action="store_true", default=True, help="save cnn model")
args.add_argument("--nettype", type=str, default="CNN",help="embedding networks")
args.add_argument("--maxl", type=int, default=80,  help="max length of strings")
args.add_argument("--project", type=str, default="")
args.add_argument("--queryfile", type=str, default="")
args.add_argument("--threshold", type=float, default=0.4)
args = args.parse_args()